### ISSUE TITLE
After I used your EFI, the startup  only has window.

### ISSUE THREAD

**Issue by iwsbiwy** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#1]
@B0hrer 
Hi,
i'm first install macos，
![default EFI.png](https://i.loli.net/2019/08/31/hcX1ZnjDzBu4xKv.png)
![use EFI.png](https://i.loli.net/2019/08/31/6JKPOeALGNSt4Hc.png)

**Comment by B0hrer** [comment]
I'm currently trying to find a solution for this. For some reason I don't really know it's currently not able to detect the installer. I'm on it and will issue a commit with the fix if I find one. Pls don't exspect too much though. I'm definitely no Hackintosh expert, but I'll try my best

**Comment by iwsbiwy** [comment]
> I'm currently trying to find a solution for this. For some reason I don't really know it's currently not able to detect the installer. I'm on it and will issue a commit with the fix if I find one. Pls don't exspect too much though. I'm definitely no Hackintosh expert, but I'll try my best

thank you。

**Comment by B0hrer** [comment]
I think I found the problem. After one of the latest Clover updates the whole UEFI driver folder structure was redone. I readded the one that I forgot to move to the new location

**Comment by B0hrer** [comment]
I just pushed a commit. The installer should now be detected again

**Comment by iwsbiwy** [comment]
> 我只是推了一个提交。现在应该再次检测安装程序

ok,i try it.

**Comment by iwsbiwy** [comment]
> I just pushed a commit. The installer should now be detected again

i try ,but isnot work.
![1.jpg](https://i.loli.net/2019/09/01/Z4nWqQ8UXJawHFg.jpg)
![2.jpg](https://i.loli.net/2019/09/01/pysqdW3mwTghXUQ.jpg)

**Comment by B0hrer** [comment]
Then I don't know. I currently do a reinstall with exactly the provided EFI, as I acciedently corrupted my macOS partition and is works just fine

**Comment by B0hrer** [comment]
You can boot with the -v flag and then you get the exact error message. The white Apple logo doesn't give any usefull information
