### ISSUE TITLE
ACPI Exception: AE_BAD_PARAMETER

### ISSUE THREAD

**Issue by SLSX** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#2]
Booting stops at 

ACPI Exception: AE_BAD_PARAMETER, Could not install PciConfig handler for Root Bridge PCI0 (20160930/evrgnini-340) 

and hangs for about half an hour. After that the messages from the attached screenshot appear.
Soon after that the screen gets garbled.

on Thinkpad x1c 5th gen 20HQ-S6J500

![Untitled](https://user-images.githubusercontent.com/8351411/65258349-09f5cf80-db03-11e9-880e-17a7aeef37e1.jpg)

**Comment by EricZQu** [comment]
I got the same problem... On 20HQ-A00SCD
After removing the DSDT.aml, it could boot but lost some of the features.
Thus you have to patch the ACPI yourself. Good luck.

**Comment by MJimitater** [comment]
I also had this error message on on Thinkpad T480s:

> ACPI Exception: AE_BAD_PARAMETER, Could not install PciConfig handler for Root Bridge PCI0

How does ACPI patching work?

**Comment by B0hrer** [comment]
Have a look at this: https://dortania.github.io/Getting-Started-With-ACPI/
