### ISSUE TITLE
Is the Thunderbolt and HDMI port working ?

### ISSUE THREAD

**Issue by sh0umik** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#3]
Please let us know if these ports are working too.

**Comment by B0hrer** [comment]
Thunderbolt is working when you plug in the TB3 device before boot. HDMI is a little buggy. I turns the internal display black once you plug in the cable. Closing and reopening the lid fixes this until the next time you reboot the Laptop

So technically they're working with some caveats
