### ISSUE TITLE
AcpiBattery non work

### ISSUE THREAD

**Issue by gianlucainnocenti** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#4]
Hi, I installed all you have posted but I have always problem with ACPIBattery..
Can you Helpme?

**Comment by B0hrer** [comment]
Whats your exact problem?

**Comment by gianlucainnocenti** [comment]
Hi thanks for answer..
I not see battery on top bar... If I enable from options it show 1 second
and then soon disappear

Il mar 7 gen 2020, 15:43 B0hrer <notifications@github.com> ha scritto:

**Comment by B0hrer** [comment]
Do you have the patched DSDT active, as well as the Kext installed? The battery indicator will only show up, if you use both of them

**Comment by gianlucainnocenti** [comment]
Can you link me necessary tool to configure all correctly?
Thank in advance

Il giorno mar 7 gen 2020 alle ore 15:51 B0hrer <notifications@github.com>
ha scritto:

**Comment by B0hrer** [comment]
These are both part of my EFI folder. For more reference though
Kext: https://bitbucket.org/RehabMan/os-x-acpi-battery-driver/downloads/
For ACPI patching I used this guide as reference: https://www.tonymacx86.com/threads/99-perfect-sierra-10-12-6-on-thinkpad-x1-carbon-5th-gen-with-dual-boot-unchanged-win7.237922/
Even though it's for Sierra, many points still hold true till today (I think). I'm no Hackintosh expert. Take this with a grain of salt

**Comment by gianlucainnocenti** [comment]
Hi Bohrer, thank you for info...I extract DSDT and made suggested patch and
now I can see battery icon with real info on charge..
😉

Il giorno mar 7 gen 2020 alle ore 16:09 B0hrer <notifications@github.com>
ha scritto:
