### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by stdevol** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#6]
Hello. I successfully installed Mac OS Mojave, but I get kernel panic after boot system (debug.log attached).

160:623 0:045 Intel HD Graphics 620 [8086:5916] :: PciRoot(0x0)\Pci(0x2,0x0)
160:669 0:045 ig-platform-id = 0x12345678
....
163:640 0:069 Custom boot screen not used because entry has unset use graphics
163:686 0:046 Closing log

Configuration:
Intel i5-7200U
Intel HD Graphics 620

**Comment by B0hrer** [comment]
You could try removing the DSDT and boot without it. If this should work you would need to patch it yourself afterwards
