### ISSUE TITLE
Sleep and Brightness problem

### ISSUE THREAD

**Issue by sweord** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#7]
Hi,
Thank you for your EFI, it worked for me.

I modified my DSDT and SSDT. But there's still some problem:
1.  Can't really sleep. When I choose "Sleep" in the menu, the screen turned to black, but power consumed still very quickly. And closing cover also do not work.
2. I can't adjust brightness from keyboard.

Are there some solution for these problem? 
Thank you very much.

**Comment by B0hrer** [comment]
Sorry for don’t answering back for so long. I switched this whole repo to OpenCore which is a mach cleaner implementation than my Clover one that still contained outdated patches etc. from up to 2 years ago. Back then I had not really a clue what I was doing.

**Comment by B0hrer** [comment]
1. Sleep is now fixed apart from Hibernation. My machine easily sleeps for hours at a time
2. brightness controls are patched in through the SSDT and should work
