### ISSUE TITLE
Shutdown issue

### ISSUE THREAD

**Issue by marioeva** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#8]
Thank you so much for the detailed guide.

I am new to hackintosh.... I’m lucky that I have exact same laptop as you.... so I just copy your open core and almost everything works right.

Only one issue is that x1c won’t shutdown or reboot. After clicking shutdown or reboot in macOS, x1 turn off the screen but it will not power off. I have to hold down the power bottom for couple seconds to force it.

Is there any solution for open core? 

Thanks

**Comment by B0hrer** [comment]
Hmm that's wierd. Are you using the same BIOS version as I do (1.45)? This is important as different BIOS versions can mess withe the ACPI patches. You could also try enabling verbose boot, so you see exactly where the shutdown gets stuck

**Comment by marioeva** [comment]
thank you for the guide.

I just found that my BIOS is 1.46 and seems Lenovo only provide 1.48 version now and it requires Windows.

If I have to live with 1.46 BIOS, which ACPI should I amend? 
I will try verbose boot and report back

**Comment by B0hrer** [comment]
ACPI is not really a field that I'm very familiar with. I mainly incorporate the patches done by @tylernguyen for the x1c6, after extensive testing. The machines are almost identical an he's way better at this stuff than I am. If he updates his BIOS I will push the changes here as well after I tested them.

However I'm afraid I can't really help you, as I lack the time and the knowledge to reallly dive into it

**Comment by tylernguyen** [comment]
@marioeva Can you please dump your unpatched ACPI? I can try and take a look.

**Comment by marioeva** [comment]
> @marioeva Can you please dump your unpatched ACPI? I can try and take a look.

You are so nice, much appreciated. 
Please see attached system report and EFI ( which is copied from here)

I did not replace the WiFi/Bluetooth card, used the original one and used appleintelwifi.kext. This is the only hardware difference

[EFI.zip](https://github.com/B0hrer/thinkpad-x1c5-hackintosh/files/4842559/EFI.zip)
[SysReport.zip](https://github.com/B0hrer/thinkpad-x1c5-hackintosh/files/4842549/SysReport.zip)

**Comment by tylernguyen** [comment]
@marioeva 

I `diff` your DSDT against mine and on first glance, it doesn't look much different and shouldn't cause any problems. Could you try removing/disabling your network card?

If that doesn't work, I suggest you start disabling kexts and acpi patches one by one until you figure out which may be causing that problem.

**Comment by marioeva** [comment]
I used open core 0.59, all default setting, then copy your kext and apci. Now 80% of time the issue is fixed.. For remaining 20% of time, the machine reboots instead of shutdown. 

Its not perfect but I can live with in

Thank you both again for the help

**Comment by tylernguyen** [comment]
@marioeva 
The issue in question is fixed by https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-EXT1-FixShutdown.dsl
Make sure that your ACPI patches are loaded in the correct order.
You need to patch USB properly. It is likely that the x5 has a different usb mapping than the x6.

**Comment by marioeva** [comment]
Thank you.
