### ISSUE TITLE
''USB device disabled'' problem (ipad pro 11)

### ISSUE THREAD

**Issue by whz97** [B0hrer/Thinkpad-x1c-5th-gen-Hackintosh#9]
Thanks a lot for this wonderful repository and the EFI you have shared! 

I am using almost the same machine as yours, Thinkpad x1c5 5gen 20HR (different from HQ). The Catalina 10.15.5 installation works pretty well, with only one problem.

Description:
When I connect my ipad pro 11' to this computer via USB, a badge showing "usb accessories disabled unplug the accessory using too much power to re-enable usb devices" pops out and this device cannot be accessed. 

Supplementary Info:
Though this ipad pro is not shown in the sidebar of Finder, it shows in System Report as "ipad" in "USB 3.0 bus":
> Current Available (mA): 500
> Current Required (mA): 500
> Extra Operating Current (mA): 1900
> Sleep Current (mA): 2400

This problem is not eliminated when the ipad is 100% charged. 

When I connect the same ipad pro to my friend's real Macbook pro, it is recognized normally, and System Report shows:
> Current Available (mA): 500
> Current Required (mA): 500
> Extra Operating Current (mA): 1600
> Sleep Current (mA): 2100

When this ipad pro is connected to the thunderbolt/USB-C port of the Thinkpad, the computer recognizes it normally (after rebooting for the thunderbolt port to work). Additionally, my iphone connects to the computer via USB with no problem.

I know Hackintosh always has this problem or that, but your configuration is really close to perfect. The functionality to connect my ipad would make my daily work a lot easier. I searched for similar issues on google and Hackintosh forums but got nothing similar, but I suspect it has something to do with the USB power limitations. Could you take a look at this issue and maybe offer some advice?

**Comment by B0hrer** [comment]
I just checked with my iPad Pro 10.5. System info shows exactly the same current numbers as for you:

>  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	1900
  Sleep current (mA):	2400

Have you tried bot USB A ports on this Laptop? I get the "usb accessories disabled unplug the accessory using too much power to re-enable usb devices" error when plugging my iPad into the left USB A port. The right (always on) port doesn't produce this error.
USB ports on my Thunderbolt docking station also work as expected (after being initialised during boot).
You should definitely check the right side USB port, as it's working for me. As for the left one I can only guess, that it's maybe wired differently and has its power delivery decreased.
